### ISSUE TITLE
Improve display Julia execution cells

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/JSOTutorials.jl#45]
We should increase the width to show properly NLPModels at least

![display_issue](https://user-images.githubusercontent.com/25304288/215519902-79e25aa9-74f3-4793-bff0-a49d2dccd0d4.png)

**Comment by abelsiqueira** [comment]
It's possible individually with this: https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/blob/5d009c0c358ba8afda7a5c073ee16643e7341c11/tutorials/using-callbacks/index.jmd#L18
We should check if it's possible to set as default in Weave.
