### ISSUE TITLE
Tutorials with errors

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/JSOTutorials.jl#65]
- [x] https://juliasmoothoptimizers.github.io/JSOTutorials.jl/introduction-to-cannoles/
- [x] https://juliasmoothoptimizers.github.io/JSOTutorials.jl/introduction-to-ripqp/
- [ ] https://juliasmoothoptimizers.github.io/JSOTutorials.jl/introduction-to-quadraticmodels/

**Comment by tmigot** [comment]
Thanks for reporting those. I am not sure to understand where to put the missing file.
We use [AFIRO.SIF](https://github.com/mlubin/jlSimplex/blob/master/AFIRO.SIF) in the QuadraticModels tutorial. I tried to put the file in all the possible folders, but none seem to work...
 `src/`, `src/tutorials/`, `src/tutorial/introduction-to-quadraticmodels`, `src/tutorial/introduction-to-quadraticmodels/figures`
Any ideas?

https://github.com/JuliaSmoothOptimizers/QuadraticModels.jl/issues/115

**Comment by dpo** [comment]
Is `MASTSIF` defined?
